joystick:
  ros__parameters:
    use_sim_time: true
    # device_id: 0
    # device_name: ""
    # deadzone: 0.5
    # autorepeat_rate: 20.0
    # sticky_buttons: false
    # coalesce_interval_ms: 1
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0